name: dev_dependency_manager
description: A new Flutter package project.
version: 0.0.1

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

  # Navigation
  go_router: ^14.2.7

  # Test
  mocktail: ^1.0.4
  bloc_test: ^9.1.7

  # Linter
  flutter_lints: ^4.0.0

flutter:
