name: morpheme
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ./core
  splash:
    path: ./features/splash
  onboarding:
    path: ./features/onboarding
  auth:
    path: ./features/auth
  home:
    path: ./features/home
  news:
    path: ./features/news
  profile:
    path: ./features/profile
  selling:
    path: ./features/selling

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  morpheme_cucumber: ^1.0.2

flutter:
  uses-material-design: true
  assets:
    - integration_test/ndjson/
