name: morpheme
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: "^3.6.0"

workspace:
  - assets
  - core
  - core/packages/dependency_manager
  - core/packages/morpheme_library
  - core/packages/dev_dependency_manager
  - features/splash
  - features/onboarding
  - features/auth
  - features/home
  - features/news
  - features/profile
  - features/selling

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ./core
  splash:
    path: ./features/splash
  onboarding:
    path: ./features/onboarding
  auth:
    path: ./features/auth
  home:
    path: ./features/home
  news:
    path: ./features/news
  profile:
    path: ./features/profile
  selling:
    path: ./features/selling

dev_dependencies:
  dev_dependency_manager:
    path: ./core/packages/dev_dependency_manager
  integration_test:
    sdk: flutter
  morpheme_cucumber: ^1.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - integration_test/ndjson/
