name: dependency_manager
description: All dependency package of project here.
version: 0.0.1

publish_to: "none"

environment:
  sdk: "^3.6.0"
  flutter: "^3.27.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  # Google Font
  google_fonts: ^6.3.0

  # Navigation
  go_router: ^14.8.1

  # Service Locator
  get_it: ^8.2.0

  # Storage
  flutter_secure_storage: ^9.2.4

  # Component
  skeletonizer: ^2.1.0

  # Utils
  async: ^2.13.0
  equatable: ^2.0.7
  collection: ^1.19.1

  # Firebase
  # firebase_core: ^2.25.4
  # firebase_analytics: ^10.8.5
  # firebase_crashlytics: ^3.4.14
  # firebase_remote_config: ^4.3.13

dev_dependencies:
  dev_dependency_manager:
    path: ../dev_dependency_manager

flutter:
  uses-material-design: true
