name: core
description: A core package in application.
version: 0.0.1

publish_to: "none"

environment:
  sdk: "^3.6.0"
  flutter: "^3.27.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #Intl for localizations
  intl: ^0.20.2

  dependency_manager:
    path: ./packages/dependency_manager
  morpheme_library:
    path: ./packages/morpheme_library
  assets:
    path: ../assets

dev_dependencies:
  dev_dependency_manager:
    path: ./packages/dev_dependency_manager

flutter:
  uses-material-design: true

