name: morpheme_library
description: A new Flutter package project.
version: 0.0.1

publish_to: "none"

environment:
  sdk: "^3.6.0"
  flutter: "^3.27.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  morpheme_base: ^2.1.0
  morpheme_http: ^6.0.0
  morpheme_extension: ^1.1.1
  morpheme_cached_network_image: ^3.3.0
  morpheme_responsive: ^0.0.4

dev_dependencies:
   dev_dependency_manager:
    path: ../dev_dependency_manager

flutter:
  uses-material-design: true
